<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="4" time="0.114" timestamp="2021-05-06T11:49:42.294070" hostname="Sharhan"><testcase classname="test_multiply" name="test_multiplication_11[1-11]" time="0.003" /><testcase classname="test_multiply" name="test_multiplication_11[2-22]" time="0.002" /><testcase classname="test_multiply" name="test_multiplication_11[3-35]" time="0.002"><failure message="assert 33 == 35&#10;  +33&#10;  -35">num = 3, output = 35

    @pytest.mark.parametrize("num, output", [(1, 11), (2, 22), (3, 35), (4, 44)])
    def test_multiplication_11(num, output):
&gt;       assert 11 * num == output
E       assert 33 == 35
E         +33
E         -35

test_multiply.py:6: AssertionError</failure></testcase><testcase classname="test_multiply" name="test_multiplication_11[4-44]" time="0.002" /></testsuite></testsuites>